{
 "title": "Personal Health Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Weight Tracking",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Weight (kg)" }
   ],
   "targets": [
    {
     "queryText": "SELECT strftime('%Y-%m-%dT%H:%M:%SZ', SUBSTR(recorded_at, 1, 19)) AS time,value\nFROM health_metrics\nJOIN metric_types ON health_metrics.metric_type_id = metric_types.id\nWHERE user_id = 1 AND metric_types.name = 'weight'\nORDER BY recorded_at",
     "rawQueryText": "SELECT strftime('%Y-%m-%dT%H:%M:%SZ', SUBSTR(recorded_at, 1, 19)) AS time,value\nFROM health_metrics\nJOIN metric_types ON health_metrics.metric_type_id = metric_types.id\nWHERE user_id = 1 AND metric_types.name = 'weight'\nORDER BY recorded_at"
    }
   ]
  },
  {
   "title": "Daily Steps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Steps" }
   ],
   "targets": [
    {
     "queryText": "SELECT strftime('%Y-%m-%dT%H:%M:%SZ', SUBSTR(recorded_at, 1, 19)) AS time,value AS steps\nFROM health_metrics\nJOIN metric_types ON health_metrics.metric_type_id = metric_types.id\nWHERE user_id = 1 AND metric_types.name = 'steps'\nORDER BY recorded_at",
     "rawQueryText": "SELECT strftime('%Y-%m-%dT%H:%M:%SZ', SUBSTR(recorded_at, 1, 19)) AS time,value AS steps\nFROM health_metrics\nJOIN metric_types ON health_metrics.metric_type_id = metric_types.id\nWHERE user_id = 1 AND metric_types.name = 'steps'\nORDER BY recorded_at"
    }
   ]
  },
  {
   "title": "Sleep Hours",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Hours" }
   ],
   "targets": [
    {
     "queryText": "SELECT strftime('%Y-%m-%dT%H:%M:%SZ', SUBSTR(recorded_at, 1, 19)) AS time,value\nFROM health_metrics\nJOIN metric_types ON health_metrics.metric_type_id = metric_types.id\nWHERE user_id = 1 AND metric_types.name = 'sleep'\nORDER BY recorded_at",
     "rawQueryText": "SELECT strftime('%Y-%m-%dT%H:%M:%SZ', SUBSTR(recorded_at, 1, 19)) AS time,value\nFROM health_metrics\nJOIN metric_types ON health_metrics.metric_type_id = metric_types.id\nWHERE user_id = 1 AND metric_types.name = 'sleep'\nORDER BY recorded_at"
    }
   ]
  },
  {
   "title": "Recent Exercise",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%Y-%m-%dT%H:%M:%SZ', SUBSTR(exercise_records.recorded_at, 1, 19)) AS time,\n  exercise_types.name AS Exercise,\n  exercise_records.duration / 60 AS Duration_Minutes,\n  exercise_records.distance AS Distance_Meters,\n  exercise_records.calories AS Calories\nFROM exercise_records\nJOIN exercise_types ON exercise_records.exercise_type_id = exercise_types.id\nWHERE user_id = 1\nORDER BY recorded_at DESC\nLIMIT 10",
     "rawQueryText": "SELECT \n  strftime('%Y-%m-%dT%H:%M:%SZ', SUBSTR(exercise_records.recorded_at, 1, 19)) AS time,\n  exercise_types.name AS Exercise,\n  exercise_records.duration / 60 AS Duration_Minutes,\n  exercise_records.distance AS Distance_Meters,\n  exercise_records.calories AS Calories\nFROM exercise_records\nJOIN exercise_types ON exercise_records.exercise_type_id = exercise_types.id\nWHERE user_id = 1\nORDER BY recorded_at DESC\nLIMIT 10"
    }
   ]
  }
 ]
}